// <auto-generated />
using System;
using LojaJogos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LojaJogos.Migrations
{
    [DbContext(typeof(LojaJogosContext))]
    [Migration("20200629234223_AddCategoria")]
    partial class AddCategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaJogos.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("LojaJogos.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Altura");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("LojaJogos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategotiaId");

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.Property<double>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("CategotiaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("LojaJogos.Models.Produto", b =>
                {
                    b.HasOne("LojaJogos.Models.Categoria", "Categotia")
                        .WithMany("Produtos")
                        .HasForeignKey("CategotiaId");
                });
#pragma warning restore 612, 618
        }
    }
}
